MIMETYPE_JSON = 'application/json'
MIMETYPE_CSV = 'text/csv'
SIRCYL_EXCHANGE_NAME = "SirCyL_Exchange"
SIRCYL_PLAN_EJECUCION_ROUTING_KEY = "Asiento_SirCyL"
SIRCYL_DOCUMENTOS_ASIENTO_ROUTING_KEY = "Documentos_Asiento_SirCyL"
TTL_ASIENTOS_SEG=300