### GET Healthcheck
GET http://localhost:5000/healthcheck
Authorization: Bearer eyJraWQiOiJkYjQzMDY1MmFkMGU5MTQ4ZmNjNzVhZWM4M2NjYmIxNDIwYTBhNWYzYjhlNWExNDBjMjM1YmQ4Nzc5Y2JlZTU1IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJJTlZFIiwiZXhwIjoyMDYxMzkyODA5LCJpc3MiOiJBVVRIWiIsImlhdCI6MTc0NjAzMjgwOSwianRpIjoieVdnemxxanQwUmhWbTdobjhqbzZBMU9pdHpydzRxdjUiLCJwcmluY2lwYWwiOiJJTlZFIn0.XO2VHoTvq0LGtccwU1nPPsIExkwX43ilPn8eUFYgrQAhPbe7qv1dytIvoW57WGb02GTq6esYQ6wwFbZPlk9qJvY6fB1f4PKICOnuGnorLhWYThPpAB-7_uxX1svtn8UlVjDRHSWkSzN3J4T0dVRBhenAclwGpOOChxvACgyKMrUmbAImqTg_anvbGBLKdoA-TScz4x5QW-MD0va2_1i-fMPJvd7JNaNDIroK97LW32UG3ktF81S3ScnkzEd1gm9CgQKz2fiLyfhw65SyJqsH794EIYxEPkP1rcrvyNWVO94JTxb9vDsAXNMRUbEiW-Zd3NgNMFgreTEFtf-iAASNHQ

### Generar plan de descarga desde el 01/01/2025 a 31/12/2025
POST http://localhost:5000/api/v1/generarPlanDescarga
Authorization: Bearer eyJraWQiOiJkYjQzMDY1MmFkMGU5MTQ4ZmNjNzVhZWM4M2NjYmIxNDIwYTBhNWYzYjhlNWExNDBjMjM1YmQ4Nzc5Y2JlZTU1IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJJTlZFIiwiZXhwIjoyMDYxMzkyODA5LCJpc3MiOiJBVVRIWiIsImlhdCI6MTc0NjAzMjgwOSwianRpIjoieVdnemxxanQwUmhWbTdobjhqbzZBMU9pdHpydzRxdjUiLCJwcmluY2lwYWwiOiJJTlZFIn0.XO2VHoTvq0LGtccwU1nPPsIExkwX43ilPn8eUFYgrQAhPbe7qv1dytIvoW57WGb02GTq6esYQ6wwFbZPlk9qJvY6fB1f4PKICOnuGnorLhWYThPpAB-7_uxX1svtn8UlVjDRHSWkSzN3J4T0dVRBhenAclwGpOOChxvACgyKMrUmbAImqTg_anvbGBLKdoA-TScz4x5QW-MD0va2_1i-fMPJvd7JNaNDIroK97LW32UG3ktF81S3ScnkzEd1gm9CgQKz2fiLyfhw65SyJqsH794EIYxEPkP1rcrvyNWVO94JTxb9vDsAXNMRUbEiW-Zd3NgNMFgreTEFtf-iAASNHQ
Content-Type: application/json
Accept: text/csv

{
  "fecha_inicio": "2025-01-01T00:00:00",
  "fecha_fin": "2025-12-31T23:59:59",
  "max_asientos": 1000
}

### Ejecutar plan de descarga desde el 01/01/2025 a 31/12/2025
POST http://localhost:5000/api/v1/ejecutarPlanDescarga
Authorization: Bearer eyJraWQiOiJkYjQzMDY1MmFkMGU5MTQ4ZmNjNzVhZWM4M2NjYmIxNDIwYTBhNWYzYjhlNWExNDBjMjM1YmQ4Nzc5Y2JlZTU1IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJJTlZFIiwiZXhwIjoyMDYxMzkyODA5LCJpc3MiOiJBVVRIWiIsImlhdCI6MTc0NjAzMjgwOSwianRpIjoieVdnemxxanQwUmhWbTdobjhqbzZBMU9pdHpydzRxdjUiLCJwcmluY2lwYWwiOiJJTlZFIn0.XO2VHoTvq0LGtccwU1nPPsIExkwX43ilPn8eUFYgrQAhPbe7qv1dytIvoW57WGb02GTq6esYQ6wwFbZPlk9qJvY6fB1f4PKICOnuGnorLhWYThPpAB-7_uxX1svtn8UlVjDRHSWkSzN3J4T0dVRBhenAclwGpOOChxvACgyKMrUmbAImqTg_anvbGBLKdoA-TScz4x5QW-MD0va2_1i-fMPJvd7JNaNDIroK97LW32UG3ktF81S3ScnkzEd1gm9CgQKz2fiLyfhw65SyJqsH794EIYxEPkP1rcrvyNWVO94JTxb9vDsAXNMRUbEiW-Zd3NgNMFgreTEFtf-iAASNHQ
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename=20251126150917.csv;

< ./20251126150917.csv